server:
  port: 8090
  servlet:
    context-path: /api
    session:
      cookie:
        max-age: 2592000
  tomcat:
    max-swallow-size: 60MB  # Tomcat吞入最大尺寸
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm  #全局日期格式
    time-zone: GMT+8
    default-property-inclusion: non_null
  application:
    name: campus
  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/campus
    username: root
    password: admin
  #设置文件上传最大为10MB，但业务逻辑中限制了单次上传最大不能超过3MB
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 60MB # 整个请求限制
      enabled: true
  #本地使用的配置
  profiles:
    active: local
  #redis配置
  redis:
    database: 1
    port: 6379
    host: 127.0.0.1
    password: xxx
    connect-timeout: 5000
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
  #session配置
  session:
    store-type: redis
    #session30天过期
    timeout: 2592000
mybatis-plus:
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: false
    #在开发环境打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete #全局逻辑删除字段
      logic-delete-value: 1 #逻辑已删除值
      logic-not-delete-value: 0 #逻辑未删除值
    enable-sql-runner: true
# 接入DeepSeek大模型
ai:
  apiKey: xxxxx
knife4j:
  enable: true
  openapi:
    title: campus
    version: v1.0a
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.xiaoyu.campus.controller
